name: CI & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    outputs:
      jar-path: ${{ steps.build.outputs.jar-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        id: build
        run: |
          mvn clean package -DskipTests
          # Сохраняем путь до JAR
          echo "jar-path=$(ls target/*.jar)" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Copy JAR via SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: ${{ needs.build.outputs.jar-path }}
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Restart application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            # Если вы запускаете через systemd:
            # sudo systemctl restart adventuretime.service
            # Или перезапускаете вручную:
            pkill -f 'java .*app.jar' || true
            nohup java -jar *.jar > app.log 2>&1 &
